[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_BASE_URL = "https://automation-dashboard-api.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200